name: "Code Analysis"

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 0 * * 0"

concurrency:
  group: ${{ format('{0}-{1}', github.workflow, github.head_ref) }}
  cancel-in-progress: true

permissions: read-all

jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - run: npm install
      - run: npm run check

  Test:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Create Milestone
        id: create
        uses: sv-tools/create-milestone-action@b13d071df1877ae13c83e9e3c796857575a38315 # v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: ${{ github.run_number }}
          description: "just created"
          state: open
      - run: echo "created - id ${{ steps.create.outputs.id }}; number ${{ steps.create.outputs.number }}"
      - name: Change by ID
        id: change-by-id
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          by_id: ${{ steps.create.outputs.id }}
          description: "changed by ID"
      - run: echo "changed by ID - ${{ steps.change-by-id.outputs.description }}"
      - name: Change by Number
        id: change-by-number
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          by_number: ${{ steps.create.outputs.number }}
          description: "changed by Number"
      - run: echo "changed by Number - ${{ steps.change-by-number.outputs.description }}"
      - name: Change by Title and Close
        id: change-by-title
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          by_title: ${{ github.run_number }}
          description: "changed by Title"
          state: "closed"
      - run: echo "changed by Title - ${{ steps.change-by-title.outputs.description }}, state ${{ steps.change-by-title.outputs.state }}"
      - name: Delete Milestone
        uses: octokit/request-action@dad4362715b7fb2ddedf9772c8670824af564f0d # v2.4.0
        with:
          route: DELETE /repos/${{ github.repository }}/milestones/${{ steps.create.outputs.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
